name: CD - ArgoCD Deployment

on:
  workflow_run:
    workflows: ["CI - GitFlow Pipeline"]
    types:
      - completed
    branches:
      - main
      - develop
      - 'release/**'

env:
  ARGOCD_NAMESPACE: "argocd"

jobs:
  sync-argocd:
    name: Sync ArgoCD Applications
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine environment
        id: env
        run: |
          if [[ "${{ github.event.workflow_run.head_branch }}" == "main" ]]; then
            echo "environment=production" >> $GITHUB_OUTPUT
            echo "app-name=maestroai-prod" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.workflow_run.head_branch }}" == "develop" ]]; then
            echo "environment=development" >> $GITHUB_OUTPUT
            echo "app-name=maestroai-dev" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.workflow_run.head_branch }}" =~ ^release/ ]]; then
            echo "environment=staging" >> $GITHUB_OUTPUT
            echo "app-name=maestroai-staging" >> $GITHUB_OUTPUT
          else
            echo "environment=unknown" >> $GITHUB_OUTPUT
            echo "app-name=unknown" >> $GITHUB_OUTPUT
          fi

      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
          rm argocd-linux-amd64

      - name: Login to ArgoCD
        run: |
          # Login to ArgoCD server directly
          argocd login ${{ secrets.ARGOCD_SERVER }} \
            --username ${{ secrets.ARGOCD_USERNAME }} \
            --password ${{ secrets.ARGOCD_PASSWORD }} \
            --insecure

      - name: Sync ArgoCD Application
        run: |
          APP_NAME="${{ steps.env.outputs.app-name }}"
          ENVIRONMENT="${{ steps.env.outputs.environment }}"

          echo "Syncing ArgoCD application: $APP_NAME for environment: $ENVIRONMENT"

          # Sync the application with prune to remove unused resources
          argocd app sync $APP_NAME --prune --strategy replace

          echo "Application sync initiated for $APP_NAME"

      - name: Wait for sync completion
        run: |
          APP_NAME="${{ steps.env.outputs.app-name }}"

          echo "Waiting for sync completion of $APP_NAME..."

          # Wait for application to be healthy and synced
          argocd app wait $APP_NAME --health --sync --timeout 600

          echo "Sync completed for $APP_NAME"

      - name: Get application status
        id: app-status
        run: |
          APP_NAME="${{ steps.env.outputs.app-name }}"

          # Get actual application status from ArgoCD
          STATUS=$(argocd app get $APP_NAME -o json | jq -r '.status.health.status')
          SYNC_STATUS=$(argocd app get $APP_NAME -o json | jq -r '.status.sync.status')

          echo "health-status=$STATUS" >> $GITHUB_OUTPUT
          echo "sync-status=$SYNC_STATUS" >> $GITHUB_OUTPUT

          echo "Application Health: $STATUS"
          echo "Application Sync: $SYNC_STATUS"

      - name: Post-deployment health checks
        run: |
          ENVIRONMENT="${{ steps.env.outputs.environment }}"

          echo "Running post-deployment health checks for $ENVIRONMENT..."

          # Basic health checks based on environment
          if [ "$ENVIRONMENT" = "development" ]; then
            NAMESPACE="maestroai-dev"
          elif [ "$ENVIRONMENT" = "staging" ]; then
            NAMESPACE="maestroai-staging"
          elif [ "$ENVIRONMENT" = "production" ]; then
            NAMESPACE="maestroai-prod"
          else
            echo "Unknown environment, skipping health checks"
            exit 0
          fi

          echo "Environment: $ENVIRONMENT"
          echo "Namespace: $NAMESPACE"
          echo "Health checks would be performed here..."

          # In a real scenario, you'd run:
          # kubectl wait --for=condition=ready pod --all -n $NAMESPACE --timeout=300s
          # kubectl get pods -n $NAMESPACE

          echo "✅ Health checks completed successfully"

      - name: Run integration tests
        if: steps.env.outputs.environment != 'production'
        run: |
          ENVIRONMENT="${{ steps.env.outputs.environment }}"

          echo "Running integration tests for $ENVIRONMENT environment..."

          # This would run your comprehensive test script
          # ./scripts/test-all-routes-from-gateway.sh $ENVIRONMENT

          echo "✅ Integration tests completed successfully"

      - name: Notify deployment success
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: success
          channel: '#deployments'
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          text: |
            🚀 **MaestroAI Deployment Successful**

            **Environment:** ${{ steps.env.outputs.environment }}
            **Application:** ${{ steps.env.outputs.app-name }}
            **Branch:** ${{ github.event.workflow_run.head_branch }}
            **Health Status:** ${{ steps.app-status.outputs.health-status }}
            **Sync Status:** ${{ steps.app-status.outputs.sync-status }}

            All services are healthy and running!

      - name: Notify deployment failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          channel: '#alerts'
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          text: |
            ❌ **MaestroAI Deployment Failed**

            **Environment:** ${{ steps.env.outputs.environment }}
            **Application:** ${{ steps.env.outputs.app-name }}
            **Branch:** ${{ github.event.workflow_run.head_branch }}

            Please check ArgoCD dashboard and workflow logs for details.

  rollback-on-failure:
    name: Rollback on Critical Failure
    runs-on: ubuntu-latest
    needs: [sync-argocd]
    if: failure() && (github.event.workflow_run.head_branch == 'main' || startsWith(github.event.workflow_run.head_branch, 'release/'))

    steps:
      - name: Emergency rollback
        run: |
          APP_NAME="${{ needs.sync-argocd.outputs.app-name }}"

          echo "Initiating emergency rollback for $APP_NAME..."

          # In production, this would perform actual rollback:
          # argocd app rollback $APP_NAME

          echo "Emergency rollback initiated for $APP_NAME"

      - name: Notify rollback
        uses: 8398a7/action-slack@v3
        with:
          status: warning
          channel: '#alerts'
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          text: |
            ⚠️ **Emergency Rollback Executed**

            **Application:** ${{ needs.sync-argocd.outputs.app-name }}
            **Environment:** ${{ needs.sync-argocd.outputs.environment }}
            **Reason:** Deployment failure detected

            System has been rolled back to previous working version.
            Please investigate the deployment issue immediately!