name: 'Build .NET Solution'
description: 'Build .NET solution with optimized configuration'
inputs:
  solution_path:
    description: 'Path to the solution file'
    required: false
    default: 'src'
  configuration:
    description: 'Build configuration'
    required: false
    default: 'Release'
runs:
  using: 'composite'
  steps:
    - name: Build solution
      shell: bash
      run: |
        # Find solution file
        SOLUTION_FILE=$(find ${{ inputs.solution_path }} -name "*.sln" 2>/dev/null | head -n 1)

        if [ -n "$SOLUTION_FILE" ]; then
          echo "Building solution: $SOLUTION_FILE"
          dotnet build "$SOLUTION_FILE" --configuration ${{ inputs.configuration }} --no-restore
        else
          echo "No solution file found in ${{ inputs.solution_path }}, trying current directory"
          SOLUTION_FILE=$(find . -name "*.sln" 2>/dev/null | head -n 1)

          if [ -n "$SOLUTION_FILE" ]; then
            echo "Building solution: $SOLUTION_FILE"
            dotnet build "$SOLUTION_FILE" --configuration ${{ inputs.configuration }} --no-restore
          else
            echo "No solution file found, building all projects"
            dotnet build --configuration ${{ inputs.configuration }} --no-restore
          fi
        fi