name: CI/CD - Library

# Calls the centralized reusable workflow for .NET libraries
# See: marcelpiva-org/maestroai-github-actions

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'fix/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-publish:
    name: Build, Test & Publish Library
    uses: marcelpiva-org/maestroai-github-actions/.github/workflows/dotnet-library.yml@main
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NUGET_API_KEY: ${{ secrets.GITHUB_TOKEN }}
